import os

Import('env')

localEnv = env.Clone()

source   = \
    [file for file in Glob('*.c') if file.name.find('iar')==-1] + \
    Glob('cc26xxware/driverlib/*.c')

localEnv.Append(
    CPPPATH =  [
    	os.path.join('#','bsp','boards','i3mote','cc26xxware'),
    	os.path.join('#','bsp','boards','i3mote','cc26xxware','inc'),
    	os.path.join('#','bsp','boards','i3mote','cc26xxware','rf_patches'),
    	os.path.join('#','bsp','boards','i3mote','cc26xxware','rom_crypto'),
    	os.path.join('#','bsp','boards','i3mote','cc26xxware','driverlib')
    ],
)

board  = localEnv.Object(source=source)

Return('board')
